services:

  # SERVICES FOR THE RASPBERRY
  raspy:
    image: ucm:humble-desktop-pi
    volumes:
      - /dev/ttyUSB0:/dev/ttyUSB0  # Monta el puerto serie
      - /dev/serial0:/dev/serial0  # Monta el otro puerto serie
      - ~/ROS2/ros_ws:/ros_ws      # Monta el workspace
    network_mode: host              
    command: /bin/bash -c "source /ros_ws/install/setup.bash && ros2 run ros_paparazzi_core raspy"
    privileged: true

  
  container:
    image: ucm:humble-desktop-pi
    volumes:
      - /dev/ttyUSB0:/dev/ttyUSB0  # Monta el puerto serie
      - /dev/serial0:/dev/serial0  # Monta el otro puerto serie
      - ~/ROS2/ros_ws:/ros_ws      # Monta el workspace
    stdin_open: true
    tty: true
    network_mode: host              
    privileged: true
    working_dir: /ros_ws/src/ros_paparazzi

  installer:
    image: ucm:humble-desktop-pi
    volumes:
      - ~/ROS2/ros_ws:/ros_ws  # Monta el workspace
    working_dir: /ros_ws/src/ros_paparazzi  # Establece el directorio de trabajo
    network_mode: host
    command: /bin/bash -c "./install.sh"  # Ejecuta el script
    privileged: true
    restart: "no"


  # SERVICES FOR THE COMPUTER
  simulator:
    image: ucm:humble-desktop
    volumes:
      - ~/ros2_ws:/ros2_ws      # Mount the workspace (change it for your own workspace)
    network_mode: host              
    command: /bin/bash -c "source /ros2_ws/install/setup.bash && ros2 launch ros_paparazzi_core sim_launch.py"
    privileged: true


  pc_installer:
    image: ucm:humble-desktop
    volumes:
      - ~/ros2_ws:/ros2_ws  # Monta el workspace
    working_dir: /ros2_ws/src/ros_paparazzi  # Establece el directorio de trabajo
    network_mode: host
    command: /bin/bash -c "./install.sh"  # Ejecuta el script
    privileged: true
    restart: "no"

  pc_container:
    image: ucm:humble-desktop
    volumes:
      - ~/ros2_ws:/ros2_ws      # Mount the workspace
    stdin_open: true
    tty: true
    network_mode: host              
    privileged: true
    working_dir: /ros2_ws/src/ros_paparazzi

  
  gcs:
    image: ucm:humble-desktop
    volumes:
      - ~/ros2_ws:/ros2_ws      # Monta el workspace
    network_mode: host              
    command: /bin/bash -c "source /ros2_ws/install/setup.bash && ros2 launch ros_paparazzi_core bokeh_launch.py"
    privileged: true